[package]
name = "mecha-wayland"
version = "0.1.0"
edition = "2024"

[dependencies]
app.workspace = true
bytemuck.workspace = true
utils.workspace = true

[workspace]
members = [
    "crates/app",
  "crates/utils"
]
resolver = "2"

[workspace.dependencies]
app = { path = "crates/app" }
utils = { path = "crates/utils" }

glam = { version = "0.29", features = ["bytemuck"] }
bytemuck = { version = "1.25.2", features = ["derive"] }
