[package]
name = "wayland"
version = "0.1.0"
edition = "2024"
build = "build/build.rs"

[dependencies]
app = { workspace = true }
ring = { workspace = true }
io-uring = { workspace = true }
libc = { workspace = true }
bitflags = { workspace = true }

[build-dependencies]
serde = { workspace = true }
quick-xml = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
prettyplease = { workspace = true }
syn = { workspace = true }
