[package]
name = "renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
app = { workspace = true }
assets = { workspace = true }
bytemuck = { workspace = true }
gbm = { version = "0.18", default-features = false }
glow = { workspace = true }
khronos-egl = { workspace = true }
layout = { workspace = true }
libc = { workspace = true }
paint = { workspace = true }
png = { workspace = true }
presentation = { workspace = true }
tracing = { workspace = true }
utils = { workspace = true }
wayland = { workspace = true }
window = { workspace = true }
