[package]
name = "text-input"
version = "0.1.0"
edition = "2024"

[dependencies]
app.workspace = true
interactivity.workspace = true
wayland.workspace = true
widgets.workspace = true

[dev-dependencies]
atlas.workspace = true
layout.workspace = true
paint.workspace = true
ring.workspace = true
wayland = { workspace = true, features = ["fake"] }
window.workspace = true
