[package]
name = "interactivity"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { workspace = true }
layout = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
assets = { workspace = true }
paint = { workspace = true }
widgets = { workspace = true }
window = { workspace = true }
