[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "counter"
path = "src/main.rs"

[dependencies]
app.workspace = true
window-manager.workspace = true
io-ring.workspace = true
wayland = { workspace = true, features = ["client"] }
renderer = { path = "../renderer" }
ui = { path = "../ui" }
widgets = { path = "../widgets" }
theme = { path = "../theme" }
assets = { path = "../assets" }
utils = { path = "../utils" }
taffy = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
assets = { path = "../assets", features = ["builder"] }
