[workspace]
members = [
    ".",
    "portal-core",
    "portals/bluetooth",
    "portals/file-chooser",
    "portals/access",
    "portals/account",
    "portals/app-chooser",
    "portals/screenshot",
    "portals/screencast",
    "portals/settings",
    "portals/notification",
    "portals/secret",
    "portals/email",
    "portals/inhibit",
    "portals/polkit-agent",
    "portals/background",
    "portals/clipboard",
    "portals/dynamic-launcher",
]

[workspace.dependencies]
app = { path = "../crates/app" }
io-ring = { path = "../crates/io-ring" }
window-manager = { path = "../crates/window-manager" }
ui = { path = "../crates/ui" }
utils = { path = "../crates/utils" }
interactivity = { path = "../crates/interactivity" }
assets = { path = "../crates/assets" }
dbus = { path = "../crates/dbus" }
zbus = { version = "5.16.0", features = ["bus-impl"] }
taffy = "0.10.1"
serde = { version = "1", features = ["derive"] }

[package]
name = "mechanix-xdg-portals"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { workspace = true }
io-ring = { workspace = true }
window-manager = { workspace = true }
dbus = { workspace = true }
portal-core = { path = "portal-core" }
bluetooth = { path = "portals/bluetooth" }
file-chooser = { path = "portals/file-chooser" }
access = { path = "portals/access" }
account = { path = "portals/account" }
app-chooser = { path = "portals/app-chooser" }
screenshot = { path = "portals/screenshot" }
screencast = { path = "portals/screencast" }
settings = { path = "portals/settings" }
notification = { path = "portals/notification" }
secret = { path = "portals/secret" }
email = { path = "portals/email" }
inhibit = { path = "portals/inhibit" }
polkit-agent = { path = "portals/polkit-agent" }
background = { path = "portals/background" }
clipboard = { path = "portals/clipboard" }
dynamic-launcher = { path = "portals/dynamic-launcher" }


